howto download
Hyperfoil/qDup pull request #140
Opened 2022-09-29 10:22 UTC by willr3

- revert to schema.json
- replace depricated methods and fix warnings
- add timeout for CI issues
- fix set-signal incrementing expected signal count and move docs
- work on how to download a file

2022-09-30 03:44 UTC, jesperpedersen requested changes

2022-09-30 03:44 UTC, jesperpedersen commented on docs/howto/download.adoc
> +This command is appropriate if the file will change or be deleted while the qDup script is running. Honestly, we rarely use `download` but
Delete last sentence

2022-09-30 03:44 UTC, jesperpedersen commented on docs/howto/download.adoc
> +We recommend using `queue-download` if you are using qDup to coordinate a performance test because some tests are impacted by the work to download a file.
We need a wird-card description

2022-10-03 16:14 UTC, willr3 commented on docs/howto/download.adoc
> +This command is appropriate if the file will change or be deleted while the qDup script is running. Honestly, we rarely use `download` but
fixed

2022-10-13 17:05 UTC, merged